---
title: "HW3"
author: "Jeff Nieman"
date: "November 14, 2015"
output: html_document
#Jeff Nieman R Homework 3

#Create a new data frame with the mushroom data

mushroom <- read.table ("file:///C:/Users/jenieman/Documents/GitHub/R-HW-Assignment-3/agaricus-lepiota.data.csv", header = FALSE, sep=',')
(mushroomtest <- mushroom [, c(1,2,3,5)])
head(mushroomtest,4)

#Rename the column names

colnames(mushroomtest) <- c("Edible", "Cap_Shape", "Cap_Surface", "Bruises")

#Transform the abbreviations to meaningful words

mushroomtest$Edible <- gsub("e", "edible", mushroomtest$Edible)
mushroomtest$Edible <- gsub("p", "poisonous", mushroomtest$Edible)
mushroomtest$Cap_Shape <- gsub("b", "bell", mushroomtest$Cap_Shape)
mushroomtest$Cap_Shape <- gsub("c", "conical", mushroomtest$Cap_Shape)
mushroomtest$Cap_Shape <- gsub("x", "convex", mushroomtest$Cap_Shape)
mushroomtest$Cap_Shape <- gsub("f", "flat", mushroomtest$Cap_Shape)
mushroomtest$Cap_Shape <- gsub("k", "knobbed", mushroomtest$Cap_Shape)
mushroomtest$Cap_Shape <- gsub("s", "sunken", mushroomtest$Cap_Shape)
mushroomtest$Cap_Surface <- gsub("g", "grooves", mushroomtest$Cap_Surface)
mushroomtest$Cap_Surface <- gsub("s", "smooth", mushroomtest$Cap_Surface)
mushroomtest$Cap_Surface <- gsub("y", "scaly", mushroomtest$Cap_Surface)
mushroomtest$Cap_Surface <- gsub("f", "fibrous", mushroomtest$Cap_Surface)
mushroomtest$Bruises <- gsub("t", "bruises", mushroomtest$Bruises)
mushroomtest$Bruises <- gsub("f", "no", mushroomtest$Bruises)
 
#Return only first 40 rows

head(mushroomtest, 40)
